### ISSUE TITLE
Distance calculation

### ISSUE THREAD

**Issue by superxin915** [hansmandersingh/mapBox#1]
**Nice work, Hans!**

I found that you use a different method to calculate the distance. 

This is the code I use:

```
(Math.sqrt(Math.pow((longitude1 - longitude2), 2) + Math.pow((latitude1 - latitude2), 2)) * 100).toFixed(1)
```

However, I found that neither you nor I have the same result as John's. 

So let's figure this out.

**Comment by hansmandersingh** [comment]
ohh i never checked John's code let me see and i'll get into checking the issue. Thanks for pointing that out

**Comment by hansmandersingh** [comment]
Hey Yuxin i checked on google maps and my results matches closest to that i think my function is ok i think john's function has got some problem. my result was 0.84 km and google maps is 0.90 km

**Comment by hansmandersingh** [comment]
Hey Yuxin thanks for pointing the issue i fixed it just now i was missing "K" in the function parameters so it was doing that. Can you check it now if it is resolved ?

**Comment by superxin915** [comment]
Cool! Found mine is wrong compares to Google's data.
